# version: "3.8"

services:
  mongo:
    image: mongo:4.4

    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    container_name: task-backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  mongo-backup:
    build: ./mongo-backup
    container_name: mongo-backup
    depends_on:
      - mongo
    volumes:
      - mongo-backup-data:/backup

  frontend:
    build:
      context: ./devops_prjct/resilient_app
      dockerfile: Dockerfile
      args:
      - REACT_APP_API_URL=http://backend:5000/tasks
    container_name: task-frontend
    
    ports:
      - "3000:3000"
    volumes:
      - ./devops_prjct/resilient_app:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true


volumes:
  mongo-data:
  mongo-backup-data:
