apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: devops_miniprjct-backend:latest

        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000  # Your backend port
        env:
        - name: MONGO_URL
          value: "mongodb://mongo-service:27017/taskdb"  # Update your DB URL
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: NodePort
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
